# numpy
### 시퀀스 데이터로부터 배열 생성

In [1]:
import numpy as np

data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
print(a1)                      # [0 1 2 3 4 5]
print(a1.dtype)                # int32

[0 1 2 3 4 5]
int32


In [2]:
data2 = [0.1, 5, 4, 12, 0.5]

a2 = np.array(data2)
print(a2)                   # [ 0.1 5. 4. 12. 0.5]
print(a2.dtype)             # float64

[ 0.1  5.   4.  12.   0.5]
float64


In [3]:
a3 = np.array([0.5, 2, 0.01, 8])

print(a3)                # [0.5 2. 0.01 8. ]
print(a3.dtype)          # float64

[0.5  2.   0.01 8.  ]
float64


### 2차원 배열

In [4]:
# 2차원 배열
a4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a4)
print(a4.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


### arrange함수로 범위를 지정해서 배열 생성

In [5]:
# np.arange(start, stop, step)
a1 = np.arange(0, 10, 2)
print(a1)                          # [0 2 4 6 8]

[0 2 4 6 8]


In [6]:
# np.arange(start, stop)
a2 = np.arange(1, 10)
print(a2)                         # [1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


In [7]:
# np.arange(stop)
a3 = np.arange(5)
print(a3)                        # [0 1 2 3 4]

[0 1 2 3 4]


In [8]:
# arange(12)로 12개의 숫자 생성후 reshape(4,3)으로 4x3 행렬을 만든다.
a4 = np.arange(12).reshape(4, 3)
print(a4) 
print(a4.shape)                 # (4, 3) 4행 3열 행렬         

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [9]:
# linspace(start, stop, num)
# 1부터 10까지 10개의 데이터 생성
a5 = np.linspace(1, 10, 10)
print(a5) 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
# 1부터 10까지 3개의 데이터 생성
a6 = np.linspace(1, 10, 3)
print(a6) 

[ 1.   5.5 10. ]


In [11]:
# 0부터 pie 까지 동일한 간격으로 나눈 20개의 데이터를 생성
a7 = np.linspace(0, np.pi, 20)
print(a7)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


### reshape 함수 : 1차원 배열을 2차원 배열로 변환
#### reshape(행의 수, 열의 수)

In [12]:
array1 = np.arange(10)                    # 0 ~ 9 까지 원소를 가진 1차원 배열
print('array1:\n', array1)

array2 = array1.reshape(2,5)              # 2행 5열  
print('array2:\n', array2)

array3 = array1.reshape(5,2)              # 5행 2열
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
array4 = np.arange(10)                   # 0 ~ 9까지 원소를 가진 1차원 배열
print(array4)

# reshape(-1, 5) : 열은 5열로 만들고, -1은 행의 수를 남은 배열의 길이와 
#                  남은 차원으로 추정해서 행을 지정하라는 의미
array5 = array4.reshape(-1,5)
print('array5 shape:', array5.shape)     #  (2, 5)
print(array5)

# reshape(5,-1) : 행은 5행으로 만들고, -1은 열의 수를 남은 배열의 길이와
#                 남은 차원으로 추정해서 열을 지정하라는 의미
array6 = array4.reshape(5,-1)
print('array6 shape:', array6.shape)    # (5, 2)
print(array6)

[0 1 2 3 4 5 6 7 8 9]
array5 shape: (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
array6 shape: (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
# 배열의 원소의 수와 차원의 수가 맞지 않으면 오류 발생한다.
array7 = np.arange(10)              # 0 ~ 9까지 원소를 가진 1차원 배열    
array8 = array7.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [15]:
array9 = np.arange(8)                       # 0 ~ 7까지 원소를 가진 1차원 배열

# 1차원 배열을 2차원 배열로 변환
array10 = array9.reshape(-1,1)
print('array10:\n',array10.tolist())        # [[0], [1], [2], [3], [4], [5], [6], [7]]
print('array10 shape:', array10.shape)      # (8,1)

# 1차원 배열을 3차원 배열로 변환
array3d = array9.reshape((2,2,2))           # 3차원 배열
print('array3d:\n', array3d.tolist())       # [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
print('array3d shape:', array3d.shape)      # (2, 2, 2)

# 3차원 배열을 2차원 배열로 변환
array11 = array3d.reshape(-1,1)
print('array11:\n',array11.tolist())        # [[0], [1], [2], [3], [4], [5], [6], [7]]
print('array11 shape:', array11.shape)      # (8,1)

array10:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array10 shape: (8, 1)
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3d shape: (2, 2, 2)
array11:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array11 shape: (8, 1)


### 특별한 형태의 배열 생성

In [16]:
import numpy as np

# zeros()함수로 원소의 갯수가 10개인 1차원 배열 생성
a1 = np.zeros(10)
print(a1) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
# zeros()함수를 이용해 3 x 4의 2차원 배열을 생성
a2 = np.zeros((3, 4))
print(a2) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# ones() 함수로 원소의 갯수가 5인 1차원 배열 생성
a3 = np.ones(5)
print(a3) 

[1. 1. 1. 1. 1.]


In [19]:
# ones() 함수로 3 x 5 인 2차원 배열 생성
a4 = np.ones((3, 5))
print(a4) 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# 3 x 3 단위 행렬 생성
a5 = np.eye(3)
print(a5) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 배열의 데이터 타입 변환 

In [21]:
# 1.문자를 원소로 갖는 numpy 배열 생성
str_a1 = np.array(['1.567','0.123','5.123','9','8'])
print(str_a1)                        # ['1.567' '0.123' '5.123' '9' '8']
print(str_a1.dtype)                  # <U5 유니코드 5자리(문자 5자리)

['1.567' '0.123' '5.123' '9' '8']
<U5


In [22]:
# astype()함수로 문자를 실수형으로 형변환
num_a1 = str_a1.astype(float)
print(num_a1)                        # [1.567 0.123 5.123 9. 8. ]
print(num_a1.dtype)                  # float64

[1.567 0.123 5.123 9.    8.   ]
float64


In [23]:
# 2.문자를 원소로 갖는 numpy 배열 생성
str_a2 = np.array(['1','3','5','7','9'])
print(str_a2)                     # ['1' '3' '5' '7' '9']
print(str_a2.dtype)               # <U1 유니코드 1자리(문자 1자리)

['1' '3' '5' '7' '9']
<U1


In [24]:
# astype()함수로 문자를 정수형으로 형변환
num_a2 = str_a2.astype(int)
print(num_a2)                    # [1 3 5 7 9]
print(num_a2.dtype)              # int32

[1 3 5 7 9]
int32


In [25]:
# 3.실수를 원소로 갖는 numpy 배열 생성
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
print(num_f1)                   # [10. 21. 0.549 4.75 5.98 ]
print(num_f1.dtype)             # float64

[10.    21.     0.549  4.75   5.98 ]
float64


In [26]:
# astype()함수로 실수를 정수형으로 형변환
num_i1 = num_f1.astype(int)
print(num_i1)                   # [10 21 0 4 5]
print(num_i1.dtype)             # int32

[10 21  0  4  5]
int32


### 난수 배열의 생성

In [27]:
# 0.0 <= r1 < 1.0 사이의 실수형태의 난수 발생
r1 = np.random.rand()
print(r1)

0.38276292771808795


In [28]:
# 0.0 <= r2 < 1.0 사이의 실수형태의 2행 3열 난수 발생
r2 = np.random.rand(2,3)
print(r2)

[[0.41580482 0.89424321 0.13122853]
 [0.98571839 0.72446666 0.97077937]]


In [29]:
# 1 <= r3 < 30 사이의 정수형태의 난수 발생
r3 = np.random.randint(1,30)
print(r3)

3


In [30]:
# 0 <= r4 < 10 사이의 정수형태의 3행 4열 난수 발생
r4 = np.random.randint(10, size=(3, 4))
print(r4)

[[0 6 2 2]
 [7 8 8 0]
 [5 7 7 7]]


### 배열의 산술 연산

In [31]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [32]:
a1 = arr1 + arr2             # 배열 더하기 : 각 원소끼리 더하기
print(a1)                    # [11 22 33 44]

[11 22 33 44]


In [33]:
a2 = arr1 - arr2            # 배열 빼기: 각 원소끼리 빼기
print(a2)                   # [ 9 18 27 36]

[ 9 18 27 36]


In [34]:
a3 = arr2 * 2              # 배열에 상수 곱하기
print(a3)                  # [2 4 6 8]

[2 4 6 8]


In [35]:
a4 = arr2 ** 2            # 배열에 거듭제곱
print(a4)                 # [ 1 4 9 16]

[ 1  4  9 16]


In [36]:
a5 = arr1 * arr2         # 배열 곱하기 : 각 원소끼리 곱함
print(a5)                # [ 10 40 90 160]

[ 10  40  90 160]


In [37]:
a6 = arr1 / arr2         # 배열 나누기 : 각 원소끼리 나눔
print(a6)                # [10. 10. 10. 10.]

[10. 10. 10. 10.]


In [38]:
a7 = arr1 / (arr2 ** 2)  # 복합 연산
print(a7)                # [ 10. 5. 3.33333333 2.5 ]

[10.          5.          3.33333333  2.5       ]


In [39]:
# 비교연산 : 각 원소와 비교해서 참이면 True, 거짓이면 False 리턴
a8 = arr1 > 20
print(a8)                # [False False True True]

[False False  True  True]


### numpy의 통계분석 함수
sum() : 원소의 합

mean() : 평균

var() : 분산

std() : 표준편차

max() : 최대값

min() : 최소값

cumsum() : 각 원소의 누적 합

cumprod() : 각 원소의 누적 곱

In [40]:
arr3 = np.arange(5)
print(arr3) 

[0 1 2 3 4]


In [41]:
sum = arr3.sum()              # 배열 각 원소의 합
print(sum)                    # 10

10


In [42]:
mean = arr3.mean()           # 배열 원소의 평균
print(mean)                  # 2.0

2.0


In [43]:
var = arr3.var()             # 분산
print(var)                   # 2.0

2.0


In [44]:
std = arr3.std()             # 표준편차
print(std)                   # 1.4142135623730951

1.4142135623730951


In [45]:
max = arr3.max()            # 최대값
print(max)                  # 4

4


In [46]:
min = arr3.min()            # 최소값
print(min)                  # 0

0


In [47]:
arr4 = np.arange(1, 5)
print(arr4)                 # [1 2 3 4]

[1 2 3 4]


In [48]:
cumsum = arr4.cumsum()      # 각 원소들의 누적합
print(cumsum)               # [ 1 3 6 10]

[ 1  3  6 10]


In [49]:
cumprod = arr4.cumprod()   # 각 원소들의 누적곱
print(cumprod)             # [ 1 2 6 24]

[ 1  2  6 24]


### 행렬 연산

In [50]:
# 2 x 2 행렬 A와 B 생성
A = np.array([0,1,2,3]).reshape(2,2)
B = np.array([3,2,0,1]).reshape(2,2)
print(A)
print(B)

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]


In [51]:
# 행렬 곱
print(A.dot(B))
print(np.dot(A,B))

[[0 1]
 [6 7]]
[[0 1]
 [6 7]]


In [52]:
# 행렬 A의 전치 행렬
print(A.transpose())
print(np.transpose(A))

[[0 2]
 [1 3]]
[[0 2]
 [1 3]]


In [53]:
# 행렬 A의 역행렬
print(np.linalg.inv(A))

[[-1.5  0.5]
 [ 1.   0. ]]


In [54]:
# 행렬 A의 행렬식
print(np.linalg.det(A))           # -2.0

-2.0


### 1차원 배열의 인덱싱

In [55]:
# 1차원 배열 정의
a1 = np.array([0, 10, 20, 30, 40, 50])
print(a1)                       # [ 0 10 20 30 40 50]

[ 0 10 20 30 40 50]


In [56]:
# index 번호 1번 위치의 원소
print(a1[1])                   # 10

10


In [57]:
# index 번호 4번 위치의 원소
print(a1[4])                   # 40

40


In [58]:
# index 번호 5번 위치의 원소값 50 -> 70으로 수정
a1[5] = 70
print(a1[5])                   # 70

70


In [59]:
# 1차원 배열에서 여러개의 원소 구하기
print(a1[[1,3,4]])            # [10 30 40]

[10 30 40]


### 2차원 배열의 인덱싱

In [60]:
# 2차원 배열 정의 : 10 ~ 90까지 10씩 증가된 배열
a2 = np.arange(10, 100, 10).reshape(3, 3)
print(a2) 

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [61]:
# 배열명[행위치, 열위치] : 0행 2열의 원소를 구함
print(a2[0, 2])                # 30

30


In [62]:
# 2행 2열의 값을 90 -> 95 로 변경
a2[2, 2] = 95
print(a2) 

[[10 20 30]
 [40 50 60]
 [70 80 95]]


In [63]:
# 2차원 배열의 1행 젂체를 변경:[40,50,60]->[45,55,65]
a2[1] = np.array([45, 55, 65])
print(a2) 

[[10 20 30]
 [45 55 65]
 [70 80 95]]


In [64]:
# 2차원 배열의 행과 열의 위치를 지정해서 여러 원소 구하기
# 배열명[ [행위치1,행위치2],[열위치1,열위치2] ]
# (0,0)위치의 원소 10, (2,1)위치의 원소 80 을 구함
print(a2[[0, 2], [0, 1]])             # [10 80]

[10 80]


In [65]:
# 2차원 배열에서 조건을 만족하는 원소 구하기
# 배열명[조건] : 조건에 맞는 원소만 구함
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])                      # [4 5 6]

[4 5 6]


### 1차원 배열의 슬라이싱

In [66]:
# 1차원 배열 정의
b1 = np.array([0, 10, 20, 30, 40, 50])
b1

array([ 0, 10, 20, 30, 40, 50])

In [67]:
# 배열[시작위치 : 끝위치]:시작위치 ~ 끝위치-1 까지 슬라이싱
# 인덱스 1 ~ 3번 원소를 슬라이싱
print(b1[1:4])                       # [10 20 30]

[10 20 30]


In [68]:
# 배열[시작위치 : ]:시작위치 ~ 끝위치 까지 슬라이싱
# 인덱스 2번 부터 끝까지 슬라이싱
print(b1[2:])                       # [20 30 40 50]

[20 30 40 50]


In [69]:
# 배열[ : 끝위치]:시작위치 ~ 끝위치-1 까지 슬라이싱
# 처음부터 인덱스 2번 까지 슬라이싱
print(b1[:3])                      # [ 0 10 20]

[ 0 10 20]


In [70]:
# 슬라이싱으로 원소의 값 변경
# 인덱스 2~4번 원소의 값을 [25, 35, 45]로 변경
b1[2:5] = np.array([25, 35, 45])
print(b1)                         # [ 0 10 25 35 45 50]

[ 0 10 25 35 45 50]


### 2차원 배열의 슬라이싱

In [71]:
# 2차원 배열 정의 : 10 ~ 90 까지 10씩 증가된 3행 3열 배열
b2 = np.arange(10, 100, 10).reshape(3,3)
print(b2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [72]:
# 배열[행 시작위치 : 행 끝위치 , 열 시작위치 : 열 끝위치]
# 1~2행, 1~2열 슬라이싱
print(b2[1:3, 1:3]) 

[[50 60]
 [80 90]]


In [73]:
# 0~2행, 1~2열 슬라이싱
print(b2[:3, 1:]) 

[[20 30]
 [50 60]
 [80 90]]


In [74]:
# 1행, 0~1열 슬라이싱
print(b2[1][0:2]) 

[40 50]


In [75]:
# 2차원 배열에서 슬라이싱 된 배열에 값을 지정
# 0~1행, 1~2열 위치에 [25, 35], [55, 65] 값 변경
b2[0:2, 1:3] = np.array([[25, 35],[55, 65]])
print(b2) 

[[10 25 35]
 [40 55 65]
 [70 80 90]]
